name: Build and Deploy iPadOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Dependencies
        run: npm install

      - name: Build iPadOS App
        run: |
          cordova platform add ios
          cordova platform add ios@latest
          cordova build ios --device --target=ipad
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: platforms/ios/build/device/*.ipa
